# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190318_0123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table=None,
        ),
    ]
