# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_num',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ttgy_user',
        ),
    ]
