# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190315_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
